server:
  address: ':4040'
  username: 'gobot'
  password: 'gobot'
context:
  timeout: 30
elasticsearch:
  urls:
    - 'https://elasticsearch.webcenter.fr'
  username: 'gobot'
  password: 'G@b@t$36'
dfp:
  id: "fat"
  name: "fat"
  port: "/dev/ttyUSB0"
  pin:
    captor:
      water_security_top: "12"
      water_security_under: "13"
      water_top: "10"
      water_under: "9"
      dht11: ""
    relay:
      barrel_motor: "3"
      washing_pump: "2"
    led:
      green: "5"
      red: "4"
    button:
      auto: "6"
      stop: "7"
      emergency_stop: "8"
      wash: "11"
      force_washing_pump: "22"
      force_barrel_motor: "23"
tfp:
  name: 'filter'
  address: '192.168.0.191:3030'
  pin:
    relay:
      pond_pomp: '0'
      waterfall_pomp: '1'
      pond_bubble: '2'
      filter_bubble: '3'
      uvc1: '4'
      uvc2: '5'