server:
  address: ":4040"
dfp:
  id: "fat"
  name: "fat"
  port: "/dev/ttyUSB0"
  washing:
    wait_time_washing_pump: 5
    duration: 10
    wait_time_between_wash: 300
    history_size: 10
  pin:
    captor:
      water_security_top: "12"
      water_security_under: "13"
      water_top: "10"
      water_under: "9"
      dht11: ""
    relay:
      barrel_motor: "3"
      washing_pump: "2"
    led:
      green: "5"
      red: "4"
    button:
      auto: "6"
      stop: "7"
      emergency_stop: "8"
      wash: "11"
      force_washing_pump: "22"
      force_barrel_motor: "23"
