version: "2"
services:
    postgres:
        image: postgres:12-alpine
        environment: 
            POSTGRES_PASSWORD: dfp
            PGDATA: /var/lib/postgresql/data/pgdata
            POSTGRES_DB: dfp
            POSTGRES_USER: dfp
        #volumes: 
        #    - /data/dfp:/var/lib/postgresql/data
        network_mode: "host"
        ports:
            - 5432:5432
    dfp:
        image: disaster37/dfp:latest
        build: 
            dockerfile: Dockerfile
            context: .
        links:
            - postgres:postgres